### ISSUE TITLE
Is that the parper only estimate Image Level AUROC? 

### ISSUE THREAD

**Issue by ashesofdream** [andreluizbvs/InsPLAD#1]
It seems that there aren't any pixel level annotation

**Comment by andreluizbvs** [comment]
Yes, there are only image-level annotations. Pixel-level annotations maybe be available in next months :)

**Comment by ashesofdream** [comment]
Thanks! And In your parper, it only show 5 category data. But in your dataset,it hava 17 class. Like glass-insulator,glass-insulator-big-shackle,glass-insulator-small-shackle...... Are you put them all to train? Or only train glass-insulator folder?

**Comment by andreluizbvs** [comment]
The 17 classes are for object detection training. For image classification and anomaly detection there are only 5 classes. Please read the ReadMe file or the paper carefully
