### ISSUE TITLE
Would like to use your data set to study on yolo

### ISSUE THREAD

**Issue by zl021369** [andreluizbvs/InsPLAD#2]
Dear Professor: Hello! In the process of reviewing your paper, I want to refer to your data set for defect detection research, but in the process of reviewing your proposed data set InsPLAD-fault, I have some questions to ask you: supervised_fault_classification\defect_supervised under its folder InsPLAD-fault, I didn't see the annotation information corresponding to related pictures. May I ask if I should refer to the annotation information of the InsPLAD-det document? Or is it supervised_fault_classification\defect_supervised this side of the information is not fully given? Looking forward to your answer. Thank you very much.

**Comment by CXJ0612** [comment]
Hi, I have the same question, have you solved this problem?

**Comment by andreluizbvs** [comment]
Hi!

InsPLAD-fault (`supervised_fault_classification\defect_supervised`) is an **Image Classification** dataset. Unlike InsPLAD-det, which is an Object Detection dataset, InsPLAD-fault has no bounding box annotations. InsPLAD-fault "annotations" are the placement of the images in different folders (good, corrosion, etc.).

For example, for the Glass Insulator object (`supervised_fault_classification\defect_supervised\glass-insulator\train`), two classes are represented by two folders: `good` and `missing-cap`. If you need a .txt file with image paths, you may find them in `supervised_fault_classification\defect_supervised\glass-insulator\annotations\image_list_val.txt`.

Most of the information you need can be found in the paper or in the README file of this project.

**Comment by zl021369** [comment]
Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "andreluizbvs/InsPLAD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月24日(星期三) 中午11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [andreluizbvs/InsPLAD] Would like to use your data set to study on yolo (Issue #2)





 
Hi!
 
InsPLAD-fault (supervised_fault_classification\defect_supervised) is an Image Classification dataset. Unlike InsPLAD-det, which is an Object Detection dataset, InsPLAD-fault has no bounding box annotations. InsPLAD-fault "annotations" are the placement of the images in different folders (good, corrosion, etc.).
 
For example, for the Glass Insulator object (supervised_fault_classification\defect_supervised\glass-insulator\train), two classes are represented by two folders: good and missing-cap. If you need a .txt file with image paths, you may find them in supervised_fault_classification\defect_supervised\glass-insulator\annotations\image_list_val.txt.
 
Most of the information you need can be found in the paper or in the README file of this project.
