### ISSUE TITLE
Is your code open source?

### ISSUE THREAD

**Issue by SuperJinggg** [andreluizbvs/InsPLAD#3]

**Comment by andreluizbvs** [comment]
May I ask what code exactly do you need/expect?

**Comment by SuperJinggg** [comment]
I would like to know about your network architecture implementation and training, and perhaps I can have a deeper understanding by combining it with the code. Thanks!

**Comment by andreluizbvs** [comment]
So, InsPLAD is actually a dataset, there is no proposed model. We used InsPLAD to benchmark SotA models in different computer vision tasks (object detection, image classification and anomaly detection/localization). These models' implementations are all available online. All the benchmarked models are listed on our paper (available in arxiv. Link in the ReadMe file). Please read carefully the ReadMe file.
